name = "tgbotapi"
main = "src/index.js"
compatibility_date = "2025-11-26"

[[d1_databases]]
binding = "FILE_DB"
database_name = "tgapi"
database_id = "561ceeb4-ecf4-4011-b028-ae45075873c2"
[env.production]
[env.production.vars]
ENVIRONMENT = "production"
BOT_TOKEN = "7722553870:AAE5-y2t0DwIhzIlN-aIKEmiJ5vWQhWp3-o"
ENCRYPTION_KEY="ffacbd9447afbe246d6dbd78f2e83b34"
ACCESS_PASSWORD="xiaobai.tgbotapi349"